### ISSUE TITLE
Debug problems and improve info-softwarecounter.py

### ISSUE THREAD

**Issue by jfernandz** [WyRe/dotfiles#1]
This issue is related with https://github.com/polybar/polybar-scripts/issues/291 I'm again having problems when running Discord from flatpak, here is the traceback

```
Traceback (most recent call last):
  File "/home/jfernandez/dotfiles/polybar/.config/polybar/polybar-scripts/./info-softwarecounter.py", line 81, in <module>
    gui_counts = Counter(get_running_guis())
  File "/home/jfernandez/dotfiles/polybar/.config/polybar/polybar-scripts/./info-softwarecounter.py", line 74, in get_running_guis
    validprocs = [
  File "/home/jfernandez/dotfiles/polybar/.config/polybar/polybar-scripts/./info-softwarecounter.py", line 75, in <listcomp>
    get_process(w[2]) for w in wlist if check_wtype(w[0]) == True and w[2] != '0'
  File "/home/jfernandez/dotfiles/polybar/.config/polybar/polybar-scripts/./info-softwarecounter.py", line 69, in get_process
    proc = get(["ps", "-p", w_id, "-o", "comm="])
  File "/home/jfernandez/dotfiles/polybar/.config/polybar/polybar-scripts/./info-softwarecounter.py", line 61, in <lambda>
    get = lambda cmd: subprocess.check_output(cmd).decode("utf-8").strip()
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ps', '-p', '5', '-o', 'comm=']' returned non-zero exit status 1.
```

The problem comes from the output of `wmctrl -lp` which reports a PID of `5` for the Discord window.

excuse me @jtambasco for the mention but I'd like to ask you for a little of help. In this task.

**Comment by jfernandz** [comment]
For example I'd like to know why did you have included [these lines](https://github.com/jfernandz/dotfiles/blob/master/polybar/.config/polybar/polybar-scripts/info-softwarecounter.py#L56-L59) if you are not using the `listed` list

```
        try:
            listed = sys.argv[1]
        except IndexError:
            listed = []
```

Thank you for your help @jtambasco

**Comment by jtambasco** [comment]
Hey, I think I'd used it early on when I wrote this program to debug it.  It appears useless now, so feel free to delete those lines :)

**Comment by jfernandz** [comment]
This issue is apparently closed because `info-softwareinfo.py` just doesn't throw any kind of exceptions because of wrong PIDs, but I should consider to implement a different method to trace these apps and print their logos. 

Anyway ... I'm doing some improvements to the script but I have to extend them and improve my scv methods. Maybe the next days I'll do a pull request to merge a few changes. :wink:
